version: '3'

services:
  main:
    image: sony2023
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: sony2023
    environment:
      - PYTHONPATH=.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CUDA_HOME=/usr/local/cuda-10.2
    volumes:
      - ".:/workspace"
    tty: true
    shm_size: '8gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]