hidden: 512
dropout: 0.5
no_decay: ['bias', 'LayerNorm.weight']
weight_decay: 0.01
eps: 1e-10
lr: 0.002
batch_size: 8
epochs: 5
data_dir: all+comp
detection: true
model: fasterrcnn1
model_layer: 18
pretrained: true